# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/securerandom/all/securerandom.rbi
#
# securerandom-0.3.1

module Random::Formatter
  def alphanumeric(n = nil, chars: nil); end
  def base64(n = nil); end
  def choose(source, n); end
  def gen_random(n); end
  def hex(n = nil); end
  def random_bytes(n = nil); end
  def urlsafe_base64(n = nil, padding = nil); end
  def uuid; end
  def uuid_v4; end
  def uuid_v7(extra_timestamp_bits: nil); end
end
module SecureRandom
  def self.bytes(n); end
  def self.gen_random(n); end
  def self.gen_random_openssl(n); end
  def self.gen_random_urandom(n); end
  extend Random::Formatter
end
